"""SSZ v0.9 status enums for validation and transport.

Defines the status hierarchy for SSZ bridge validation.
"""

from enum import Enum, auto


class SSZValidationStatus(Enum):
    """Validation status for SSZ gates."""
    NOT_RUN = "NOT_RUN"
    PASS = "PASS"
    FAIL = "FAIL"
    WARNING = "WARNING"
    PENDING = "PENDING"
    PROXY_ONLY = "PROXY_ONLY"


class TransportMode(Enum):
    """Transport mode classification."""
    CONTINUOUS_WORLDLINE = "CONTINUOUS_WORLDLINE"
    COPY_RECONSTRUCTION = "COPY_RECONSTRUCTION"
    DESTRUCTIVE_SCAN = "DESTRUCTIVE_SCAN"
    UNDEFINED = "UNDEFINED"


class TransportReadiness(Enum):
    """Transport readiness hierarchy per SSZ v0.9."""
    MATH_CANDIDATE_ONLY = "MATH_CANDIDATE_ONLY"
    SEGMENTATION_PASS = "SEGMENTATION_PASS"
    EFFECTIVE_DISTANCE_PROXY_PASS = "EFFECTIVE_DISTANCE_PROXY_PASS"
    SEGMENT_OVERLAP_PROXY_PASS = "SEGMENT_OVERLAP_PROXY_PASS"
    WORLDLINE_CONTINUITY_PROXY_PASS = "WORLDLINE_CONTINUITY_PROXY_PASS"
    NO_COPY_CONSTRAINT_PASS = "NO_COPY_CONSTRAINT_PASS"
    TENSOR_PENDING = "TENSOR_PENDING"
    ENERGY_PENDING = "ENERGY_PENDING"
    BIOLOGICAL_NOT_VALIDATED = "BIOLOGICAL_NOT_VALIDATED"
    EXPERIMENTALLY_UNVALIDATED = "EXPERIMENTALLY_UNVALIDATED"


class SegmentationStatus(Enum):
    """Status of SSZ segmentation validation."""
    XI_UNDEFINED = "XI_UNDEFINED"
    XI_NON_FINITE = "XI_NON_FINITE"
    XI_NEGATIVE = "XI_NEGATIVE"
    D_NON_POSITIVE = "D_NON_POSITIVE"
    S_NON_POSITIVE = "S_NON_POSITIVE"
    LORENTZIAN_VIOLATION = "LORENTZIAN_VIOLATION"
    DETERMINANT_SINGULAR = "DETERMINANT_SINGULAR"
    SEGMENTATION_PASS = "SEGMENTATION_PASS"


class WorldlineStatus(Enum):
    """Status of continuous worldline validation."""
    TAU_NOT_MONOTONIC = "TAU_NOT_MONOTONIC"
    COORDINATE_JUMP = "COORDINATE_JUMP"
    DUPLICATE_BRANCH = "DUPLICATE_BRANCH"
    D_TAU_NON_POSITIVE = "D_TAU_NON_POSITIVE"
    COORDINATE_NAN = "COORDINATE_NAN"
    WORLDLINE_PASS = "WORLDLINE_PASS"


class NoCopyStatus(Enum):
    """Status of no-copy constraint validation."""
    COPY_MODE_DETECTED = "COPY_MODE_DETECTED"
    DESTRUCTIVE_STEP_DETECTED = "DESTRUCTIVE_STEP_DETECTED"
    PATTERN_BUFFER_PRIMARY = "PATTERN_BUFFER_PRIMARY"
    DUPLICATE_INSTANCE = "DUPLICATE_INSTANCE"
    NO_COPY_PASS = "NO_COPY_PASS"
